# Generated by Django 3.0.8 on 2020-07-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=5000)),
                ('pdf', models.FileField(upload_to='notes')),
            ],
            options={
                'ordering': ['notes_id'],
            },
        ),
    ]
