# Generated by Django 3.0.8 on 2020-07-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='notes'),
        ),
    ]
