# Generated by Django 2.2 on 2020-08-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200718_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
