# Generated by Django 2.2 on 2020-08-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200806_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['notes_id', 'date_time']},
        ),
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
